### ISSUE TITLE
可否添加触发关键词

### ISSUE THREAD

**Issue by ZHLHZHU** [imxiny/utools-websocket#1]
感谢开发好用的插件( •̀ ω •́ )✧
该插件是否可以考虑添加触发关键词 `ws` / `wss`，现在websocket的关键词有点过长了😂

**Comment by imxiny** [comment]
https://testyao.oss-cn-beijing.aliyuncs.com/1624253371973.png

可使用自动化助手插件实现该功能，详见图片
